# Server
server.port=8080
spring.application.name=ChatApp Backend

# Security
spring.security.user.name=admin
spring.security.user.password=admin

# Firebase
firebase.project-id=chatapp-2ac37

# JPA warning disable
spring.jpa.open-in-view=false